# Generated by Django 5.1.4 on 2025-01-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Упражнения",
            },
        ),
        migrations.CreateModel(
            name="TargetMuscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Функции мышцы"),
                ),
            ],
            options={
                "verbose_name": "Целевая мышца",
                "verbose_name_plural": "Целевые мышцы",
            },
        ),
        migrations.CreateModel(
            name="Repetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set", models.IntegerField()),
                ("repetition", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training.exercise",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="target_muscle",
            field=models.ManyToManyField(
                to="training.targetmuscle", verbose_name="Список целевых мышц"
            ),
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название тренировки"
                    ),
                ),
                ("time_to_breathe", models.IntegerField()),
                (
                    "exercises",
                    models.ManyToManyField(
                        through="training.Repetition",
                        to="training.exercise",
                        verbose_name="Список упражнений",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="repetition",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="training.training"
            ),
        ),
    ]
