# Generated by Django 5.1.4 on 2025-01-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repetition",
            options={"verbose_name": "Повторения", "verbose_name_plural": "Повторения"},
        ),
        migrations.AlterModelOptions(
            name="training",
            options={"verbose_name": "Тренировка", "verbose_name_plural": "Тренировки"},
        ),
        migrations.AddField(
            model_name="repetition",
            name="weight",
            field=models.FloatField(blank=True, null=True, verbose_name="Рабочий вес"),
        ),
    ]
