# Generated by Django 5.1.4 on 2025-01-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_alter_repetition_options_alter_training_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repetition",
            options={
                "ordering": ["number"],
                "verbose_name": "Повторения",
                "verbose_name_plural": "Повторения",
            },
        ),
        migrations.AddField(
            model_name="repetition",
            name="number",
            field=models.IntegerField(
                null=True, verbose_name="Порядковый номер в тренировке"
            ),
        ),
        migrations.AlterField(
            model_name="repetition",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="training.exercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.AlterField(
            model_name="repetition",
            name="repetition",
            field=models.IntegerField(verbose_name="Количество повторений"),
        ),
        migrations.AlterField(
            model_name="repetition",
            name="set",
            field=models.IntegerField(verbose_name="Количество подходов"),
        ),
        migrations.AlterField(
            model_name="repetition",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="training.training",
                verbose_name="Tренировка",
            ),
        ),
    ]
