# Generated by Django 5.1.4 on 2025-01-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_alter_repetition_options_repetition_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repetition",
            name="number",
            field=models.IntegerField(verbose_name="Порядковый номер в тренировке"),
        ),
    ]
